// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfHVJtEFBDP9Db-l_qUuey63mbeaAt5KQ',
    appId: '1:222160994742:web:0c332e21948ee5e73e8117',
    messagingSenderId: '222160994742',
    projectId: 'kitchenassistant-9befd',
    authDomain: 'kitchenassistant-9befd.firebaseapp.com',
    storageBucket: 'kkitchenassistant-9befd.appspot.com',
    measurementId: 'G-YMQEXRJPBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRLCesmJY2MkC1lHLYtuBZ6wFBz1biME8',
    appId: '1:222160994742:android:8bb92350b66f8c8f3e8117',
    messagingSenderId: '222160994742',
    projectId: 'kitchenassistant-9befd',
    storageBucket: 'kitchenassistant-9befd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDu9aoDc7IKzmrA4XtAlD-N8lSvUGXrpc',
    appId: '1:222160994742:ios:39d1c9de37736a023e8117',
    messagingSenderId: '222160994742',
    projectId: 'kitchenassistant-9befd',
    storageBucket: 'kitchenassistant-9befd.appspot.com',
    iosBundleId: 'com.example.kitchenAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDu9aoDc7IKzmrA4XtAlD-N8lSvUGXrpc',
    appId: '1:222160994742:ios:39d1c9de37736a023e8117',
    messagingSenderId: '222160994742',
    projectId: 'kitchenassistant-9befd',
    storageBucket: 'kkitchenassistant-9befd.appspot.com',
    iosBundleId: 'com.example.kitchenAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfHVJtEFBDP9Db-l_qUuey63mbeaAt5KQ',
    appId: '1:222160994742:web:2430afe6fa78b87b3e8117',
    messagingSenderId: '222160994742',
    projectId: 'kitchenassistant-9befd',
    authDomain: 'kitchenassistant-9befd.firebaseapp.com',
    storageBucket: 'kitchenassistant-9befd.appspot.com',
    measurementId: 'G-HRYGK96797',
  );
}
